# Generated by Django 3.0.9 on 2020-09-22 00:29

import db.utils
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AbstractStudyObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objectId', models.IntegerField()),
                ('name', models.TextField(null=True)),
                ('studyObjectTypes', models.IntegerField(choices=[(1, 'SECTION'), (2, 'SECTIONELEMENT'), (3, 'TEXTBLOCK'), (4, 'ABSTRACTQUESTION'), (5, 'VIBRATIONPATTERN')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('userPermission', models.IntegerField(choices=[(1, 'PARTICIPANT'), (2, 'CREATOR'), (3, 'ADMINISTRATOR')], default=db.utils.PermissionTypes['PARTICIPANT'])),
            ],
        ),
        migrations.CreateModel(
            name='DateAnswer',
            fields=[
                ('abstractanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.AbstractAnswer')),
                ('answer', models.DateField()),
            ],
            bases=('db.abstractanswer',),
        ),
        migrations.CreateModel(
            name='DateQuestion',
            fields=[
                ('abstractstudyobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.AbstractStudyObject')),
                ('questionText', models.TextField()),
                ('displayName', models.TextField()),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('db.abstractstudyobject',),
        ),
        migrations.CreateModel(
            name='LinearScaleAnswer',
            fields=[
                ('abstractanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.AbstractAnswer')),
                ('answer', models.IntegerField()),
            ],
            bases=('db.abstractanswer',),
        ),
        migrations.CreateModel(
            name='LinearScaleQuestion',
            fields=[
                ('abstractstudyobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.AbstractStudyObject')),
                ('questionText', models.TextField()),
                ('displayName', models.TextField()),
                ('numberOfChoices', models.IntegerField()),
                ('leftLabel', models.TextField()),
                ('rightLabel', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('db.abstractstudyobject',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswer',
            fields=[
                ('abstractanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.AbstractAnswer')),
                ('answer', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
            bases=('db.abstractanswer',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('abstractstudyobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.AbstractStudyObject')),
                ('questionText', models.TextField()),
                ('displayName', models.TextField()),
                ('answerOptions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('maxChoices', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('db.abstractstudyobject',),
        ),
        migrations.CreateModel(
            name='QualificationQuestion',
            fields=[
                ('abstractstudyobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.AbstractStudyObject')),
                ('questionText', models.TextField()),
                ('displayName', models.TextField()),
                ('requiredAnswer', models.BooleanField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('db.abstractstudyobject',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('abstractstudyobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.AbstractStudyObject')),
                ('resultRelevant', models.BooleanField()),
                ('skippable', models.BooleanField()),
                ('randomStrategy', models.IntegerField(choices=[(1, 'NONE'), (2, 'STANDARD')], default=db.utils.RandomizingStrategies['STANDARD'])),
            ],
            bases=('db.abstractstudyobject',),
        ),
        migrations.CreateModel(
            name='SectionElement',
            fields=[
                ('abstractstudyobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.AbstractStudyObject')),
                ('randomStrategy', models.IntegerField(choices=[(1, 'NONE'), (2, 'STANDARD')], default=db.utils.RandomizingStrategies['STANDARD'])),
                ('skippable', models.BooleanField()),
                ('resultRelevant', models.BooleanField()),
            ],
            bases=('db.abstractstudyobject',),
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('abstractstudyobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.AbstractStudyObject')),
                ('text', models.TextField(null=True)),
            ],
            bases=('db.abstractstudyobject',),
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('abstractstudyobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.AbstractStudyObject')),
                ('questionText', models.TextField()),
                ('displayName', models.TextField()),
                ('length', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('db.abstractstudyobject',),
        ),
        migrations.CreateModel(
            name='VibrationPattern',
            fields=[
                ('abstractstudyobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.AbstractStudyObject')),
                ('randomStrategy', models.IntegerField(choices=[(1, 'NONE'), (2, 'STANDARD')], default=db.utils.RandomizingStrategies['STANDARD'])),
            ],
            bases=('db.abstractstudyobject',),
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('studyStatus', models.IntegerField(choices=[(1, 'CREATED'), (2, 'PUBLISHED'), (3, 'FINISHED')], default=db.utils.StudyStatus['CREATED'])),
                ('shortDescription', models.CharField(max_length=500)),
                ('fullDescription', models.TextField()),
                ('isAmpliutdeNecessary', models.BooleanField(default=False)),
                ('name', models.TextField()),
                ('randomStrategy', models.IntegerField(choices=[(1, 'NONE'), (2, 'STANDARD')], default=db.utils.RandomizingStrategies['STANDARD'])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.User', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceTuple',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('containerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_id', to='db.AbstractStudyObject')),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_id', to='db.AbstractStudyObject')),
                ('studyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Study')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('studyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Study')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.User')),
            ],
        ),
        migrations.AddField(
            model_name='abstractstudyobject',
            name='studyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Study'),
        ),
        migrations.AddField(
            model_name='abstractanswer',
            name='studyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Study'),
        ),
        migrations.AddField(
            model_name='abstractanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.User'),
        ),
        migrations.CreateModel(
            name='VibrationPatternElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('amplitude', models.IntegerField()),
                ('order', models.IntegerField()),
                ('studyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Study')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.VibrationPattern')),
            ],
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('abstractanswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.AbstractAnswer')),
                ('answer', models.TextField()),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.TextQuestion')),
            ],
            bases=('db.abstractanswer',),
        ),
        migrations.CreateModel(
            name='SectionToSectionElementRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('isFixed', models.BooleanField(default=True)),
                ('studyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Study')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Section')),
                ('sectionElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.SectionElement')),
            ],
        ),
        migrations.CreateModel(
            name='SectionOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('isFixed', models.BooleanField(default=True)),
                ('studyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Study')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Section')),
            ],
        ),
        migrations.CreateModel(
            name='SectionElementToStudyObjectRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('isFixed', models.BooleanField(default=True)),
                ('studyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Study')),
                ('studyObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.AbstractStudyObject')),
                ('sectionElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SectionElementAsContainer', to='db.SectionElement')),
            ],
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('studyId', 'userId'), name='Uniquenes of studyId and userId'),
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.MultipleChoiceQuestion'),
        ),
        migrations.AddField(
            model_name='linearscaleanswer',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.LinearScaleQuestion'),
        ),
        migrations.AddField(
            model_name='dateanswer',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.DateQuestion'),
        ),
        migrations.AddConstraint(
            model_name='abstractstudyobject',
            constraint=models.UniqueConstraint(fields=('studyId', 'objectId'), name='Uniquenes of studyId and objectId'),
        ),
    ]
