# Generated by Django 2.2.11 on 2020-09-23 09:17

import db.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='randomStrategy',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'STANDARD')], default=db.utils.RandomizingStrategies(1)),
        ),
        migrations.AlterField(
            model_name='sectionelement',
            name='randomStrategy',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'STANDARD')], default=db.utils.RandomizingStrategies(1)),
        ),
        migrations.AlterField(
            model_name='study',
            name='randomStrategy',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'STANDARD')], default=db.utils.RandomizingStrategies(1)),
        ),
        migrations.AlterField(
            model_name='study',
            name='studyStatus',
            field=models.IntegerField(choices=[(0, 'CREATED'), (1, 'PUBLISHED'), (2, 'FINISHED')], default=db.utils.StudyStatus(0)),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPermission',
            field=models.IntegerField(choices=[(0, 'PARTICIPANT'), (1, 'CREATOR'), (2, 'ADMINISTRATOR')], default=db.utils.PermissionTypes(0)),
        ),
        migrations.AlterField(
            model_name='vibrationpattern',
            name='randomStrategy',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'STANDARD')], default=db.utils.RandomizingStrategies(1)),
        ),
    ]
