# Generated by Django 2.2.11 on 2021-01-01 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20200923_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.TextField()),
                ('device', models.TextField()),
                ('display', models.TextField()),
                ('hardware', models.TextField()),
                ('manufacturer', models.TextField()),
                ('model', models.TextField()),
                ('product', models.TextField()),
                ('androidsdk', models.IntegerField()),
                ('timeInMs', models.IntegerField()),
                ('hasAmplitude', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswerOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answerOption', models.TextField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='datequestion',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='linearscalequestion',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='answerOptions',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='qualificationquestion',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='textquestion',
            name='displayName',
        ),
        migrations.AddField(
            model_name='abstractanswer',
            name='participantId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.Participant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abstractstudyobject',
            name='displayName',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='abstractanswer',
            constraint=models.UniqueConstraint(fields=('studyId', 'user', 'order', 'participantId'), name='Uniquenes of studyId and user and order'),
        ),
        migrations.AddField(
            model_name='multiplechoiceoption',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.MultipleChoiceQuestion'),
        ),
        migrations.AddField(
            model_name='multiplechoiceansweroption',
            name='multipleChoiceAnswerRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.MultipleChoiceAnswer'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Participant'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Study'),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='db.User', verbose_name='User'),
        ),
    ]
